{{- if .Values.backend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sage.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sage.backend.selectorLabels" . | nindent 4 }}
  {{- with .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.backend.ingress.className }}
  ingressClassName: {{ .Values.backend.ingress.className }}
  {{- end }}
  {{- with .Values.backend.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - {{- if .Values.backend.ingress.host }}
      host: {{ .Values.backend.ingress.host }}
      {{- end }}
      http:
        paths:
          - path: {{ .Values.backend.ingress.path }}
            pathType: {{ .Values.backend.ingress.pathType }}
            backend:
              service:
                name: {{ include "sage.backend.fullname" . }}
                port:
                  number: {{ .Values.backend.port }}
{{- end }}
