apiVersion: v1
kind: Service
metadata:
  name: {{ include "sage.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sage.backend.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
  selector:
    {{- include "sage.backend.selectorLabels" . | nindent 4 }}
